version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app/src'

  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
